// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// count_levels_num
IntegerVector count_levels_num(NumericVector x);
RcppExport SEXP _inspectdf_count_levels_num(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(count_levels_num(x));
    return rcpp_result_gen;
END_RCPP
}
// count_levels_char
IntegerVector count_levels_char(CharacterVector x);
RcppExport SEXP _inspectdf_count_levels_char(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(count_levels_char(x));
    return rcpp_result_gen;
END_RCPP
}
// na_numeric
int na_numeric(NumericVector x);
RcppExport SEXP _inspectdf_na_numeric(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(na_numeric(x));
    return rcpp_result_gen;
END_RCPP
}
// na_character
int na_character(CharacterVector x);
RcppExport SEXP _inspectdf_na_character(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(na_character(x));
    return rcpp_result_gen;
END_RCPP
}
// na_logical
int na_logical(LogicalVector x);
RcppExport SEXP _inspectdf_na_logical(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(na_logical(x));
    return rcpp_result_gen;
END_RCPP
}
// na_integer
int na_integer(IntegerVector x);
RcppExport SEXP _inspectdf_na_integer(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(na_integer(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_inspectdf_count_levels_num", (DL_FUNC) &_inspectdf_count_levels_num, 1},
    {"_inspectdf_count_levels_char", (DL_FUNC) &_inspectdf_count_levels_char, 1},
    {"_inspectdf_na_numeric", (DL_FUNC) &_inspectdf_na_numeric, 1},
    {"_inspectdf_na_character", (DL_FUNC) &_inspectdf_na_character, 1},
    {"_inspectdf_na_logical", (DL_FUNC) &_inspectdf_na_logical, 1},
    {"_inspectdf_na_integer", (DL_FUNC) &_inspectdf_na_integer, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_inspectdf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
