# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

count_levels_num <- function(x) {
    .Call(`_reporter_count_levels_num`, x)
}

count_levels_char <- function(x) {
    .Call(`_reporter_count_levels_char`, x)
}

na_numeric <- function(x) {
    .Call(`_reporter_na_numeric`, x)
}

na_character <- function(x) {
    .Call(`_reporter_na_character`, x)
}

na_logical <- function(x) {
    .Call(`_reporter_na_logical`, x)
}

na_integer <- function(x) {
    .Call(`_reporter_na_integer`, x)
}

